// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";

import {Groth16Verifier} from "../src/Verifier.sol";
import {ZKComplianceRegistry} from "../src/ZKComplianceRegistry.sol";
import {KYCToken} from "../src/KYCToken.sol";

/// @title RealProofTest
/// @notice End-to-end proof of the wiring: a REAL Groth16 proof (checked-in
///         fixture, generated by test/circuit/gen-fixture.mjs from the same
///         circuit and zkey that produced src/Verifier.sol) is redeemed through
///         the real {Groth16Verifier}, verifying the address binding and the full
///         redeem → mint flow against the actual verifier rather than a mock.
/// @dev The unit suites drive every logical branch with a mock; this one proves
///      the generated verifier and the registry agree on a genuine proof, so a
///      circuit/zkey/verifier drift fails the build loudly.
contract RealProofTest is Test {
    Groth16Verifier internal verifier;
    ZKComplianceRegistry internal registry;

    // Must match the fixture (test/circuit/gen-fixture.mjs).
    address internal constant HOLDER = address(0xAA);
    uint256 internal constant EXPIRY = 4102444800;

    uint256[2] internal pA;
    uint256[2][2] internal pB;
    uint256[2] internal pC;
    uint256[4] internal pubSignals;
    uint256 internal fixtureRoot;
    uint256 internal fixtureNullifier;

    function setUp() public {
        string memory json = vm.readFile("test/fixtures/kycpass-proof.json");
        uint256[] memory a = vm.parseJsonUintArray(json, ".pA");
        uint256[] memory b0 = vm.parseJsonUintArray(json, ".pB0");
        uint256[] memory b1 = vm.parseJsonUintArray(json, ".pB1");
        uint256[] memory c = vm.parseJsonUintArray(json, ".pC");
        uint256[] memory pub = vm.parseJsonUintArray(json, ".pubSignals");

        pA[0] = a[0];
        pA[1] = a[1];
        pB[0][0] = b0[0];
        pB[0][1] = b0[1];
        pB[1][0] = b1[0];
        pB[1][1] = b1[1];
        pC[0] = c[0];
        pC[1] = c[1];
        for (uint256 i = 0; i < 4; i++) {
            pubSignals[i] = pub[i];
        }
        fixtureNullifier = pub[0];
        fixtureRoot = pub[1];

        verifier = new Groth16Verifier();
        registry = new ZKComplianceRegistry(address(verifier), fixtureRoot, address(this));
    }

    /// @notice The real verifier accepts the fixture proof directly.
    function test_RealVerifier_AcceptsFixtureProof() public view {
        assertTrue(verifier.verifyProof(pA, pB, pC, pubSignals), "generated verifier accepts real proof");
    }

    /// @notice The bound holder redeems the real proof and becomes verified.
    function test_RealProof_RedeemVerifiesHolder() public {
        assertFalse(registry.isVerified(HOLDER));

        vm.prank(HOLDER);
        registry.redeemProof(pA, pB, pC, pubSignals);

        assertTrue(registry.isVerified(HOLDER), "holder verified after redeem");
        assertEq(registry.verifiedUntil(HOLDER), EXPIRY, "expiry recorded");
        assertTrue(registry.spentNullifiers(fixtureNullifier), "nullifier spent");
    }

    /// @notice Anti-theft address binding holds against a REAL proof: the same
    ///         proof presented from a different address is rejected before the
    ///         verifier is even consulted.
    function test_RealProof_RejectedFromOtherAddress() public {
        vm.prank(address(0xBB));
        vm.expectRevert(abi.encodeWithSelector(ZKComplianceRegistry.AddressMismatch.selector, address(0xBB)));
        registry.redeemProof(pA, pB, pC, pubSignals);
    }

    /// @notice A real proof against a stale root does not redeem.
    function test_RealProof_RejectedOnRotatedRoot() public {
        registry.setRoot(uint256(keccak256("some-other-epoch")));
        vm.prank(HOLDER);
        vm.expectRevert(
            abi.encodeWithSelector(
                ZKComplianceRegistry.RootMismatch.selector, fixtureRoot, registry.currentRoot()
            )
        );
        registry.redeemProof(pA, pB, pC, pubSignals);
    }

    /// @notice The full seed narrative in miniature: redeem a real proof, then be
    ///         minted compliant tokens the gate now permits.
    function test_RealProof_RedeemThenMint() public {
        KYCToken token = new KYCToken("ACME RWA Share", "ACME", address(registry), address(this));

        vm.prank(HOLDER);
        registry.redeemProof(pA, pB, pC, pubSignals);

        token.mint(HOLDER, 5000 ether);
        assertEq(token.balanceOf(HOLDER), 5000 ether);
        assertEq(token.totalSupply(), 5000 ether);
    }

    /*//////////////////////////////////////////////////////////////
                         VERIFIER EDGE CASES
    //////////////////////////////////////////////////////////////*/

    /// @dev The BN254 scalar field modulus, identical to the `r` constant in
    ///      {Groth16Verifier}. Public signals must be reduced mod r; the
    ///      generated verifier's `checkField` returns false for anything at or
    ///      above it, BEFORE any pairing work is attempted.
    ///
    ///      These tests exist because `docs/slither-exclusions.md` justifies the
    ///      `src/Verifier.sol` coverage exclusion by saying the residual
    ///      uncovered code is the assembly early-exits taken when the BN254
    ///      precompiles themselves fail, and that inputs which are merely wrong
    ///      are rejected by the reachable `checkField` branch, "which *is*
    ///      covered". That sentence was true in zk-escrow, which carries the
    ///      equivalent tests, and NOT true here: branch coverage on this file
    ///      read 0.00% (0/3). PF-S134 makes the claim true by writing the tests
    ///      rather than by softening the prose.
    ///
    ///      The boundary is exact and is the case worth pinning: `checkField`
    ///      tests `lt(v, r)`, so v == r must be rejected. One of these uses
    ///      exactly r for that reason.
    uint256 internal constant SCALAR_FIELD =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    /// @dev This circuit exposes FOUR public signals — nullifier, root, bound
    ///      address, expiry — and the verifier calls `checkField` on each one,
    ///      so each call site gets its own test. zk-escrow's circuit exposes
    ///      three; this is the same shape widened to the fourth signal rather
    ///      than a different one.
    function _pubSignalsWith(uint256 index, uint256 value) internal view returns (uint256[4] memory bad) {
        bad = pubSignals;
        bad[index] = value;
    }

    function test_Verifier_RejectsOutOfRangeNullifier() public view {
        // Exactly r — the boundary `lt(v, r)` must reject.
        assertFalse(verifier.verifyProof(pA, pB, pC, _pubSignalsWith(0, SCALAR_FIELD)), "rejected");
    }

    function test_Verifier_RejectsOutOfRangeRoot() public view {
        assertFalse(verifier.verifyProof(pA, pB, pC, _pubSignalsWith(1, SCALAR_FIELD + 1)), "rejected");
    }

    function test_Verifier_RejectsOutOfRangeBoundAddress() public view {
        assertFalse(verifier.verifyProof(pA, pB, pC, _pubSignalsWith(2, type(uint256).max)), "rejected");
    }

    function test_Verifier_RejectsOutOfRangeExpiry() public view {
        assertFalse(verifier.verifyProof(pA, pB, pC, _pubSignalsWith(3, SCALAR_FIELD)), "rejected");
    }

    /// @dev A point that is not on the curve makes the ecAdd/ecMul precompile
    ///      fail, which is a different rejection path from a well-formed but
    ///      wrong proof.
    function test_Verifier_RejectsOffCurvePoint() public view {
        uint256[2] memory offCurveA = [uint256(1), uint256(3)];
        assertFalse(verifier.verifyProof(offCurveA, pB, pC, pubSignals), "rejected");
    }

    function test_Verifier_RejectsZeroProof() public view {
        uint256[2] memory zeroA;
        uint256[2][2] memory zeroB;
        uint256[2] memory zeroC;
        assertFalse(verifier.verifyProof(zeroA, zeroB, zeroC, pubSignals), "rejected");
    }

    /// @notice The registry surfaces a verifier rejection as {InvalidProof},
    ///         whatever the underlying reason — here an out-of-range nullifier,
    ///         which passes every registry-level check (root, bound address,
    ///         expiry and not-yet-spent all still hold) and is stopped only by
    ///         `checkField` inside the generated verifier.
    function test_Redeem_RevertsOnOutOfRangeNullifier() public {
        vm.prank(HOLDER);
        vm.expectRevert(ZKComplianceRegistry.InvalidProof.selector);
        registry.redeemProof(pA, pB, pC, _pubSignalsWith(0, SCALAR_FIELD));
    }

    /// @notice A spent nullifier cannot be redeemed a second time, even with a
    ///         genuine proof.
    function test_RealProof_NullifierCannotReplay() public {
        vm.prank(HOLDER);
        registry.redeemProof(pA, pB, pC, pubSignals);

        vm.prank(HOLDER);
        vm.expectRevert(
            abi.encodeWithSelector(ZKComplianceRegistry.NullifierAlreadySpent.selector, fixtureNullifier)
        );
        registry.redeemProof(pA, pB, pC, pubSignals);
    }
}
